development:
  adapter: mysql2
  host: localhost
  user: root
  password: ''
  database: todo
  max_connections: 10

production: mysql2://b12366a846ffee:d6ad316d@us-cdbr-iron-east-05.cleardb.net/heroku_94ac056803a837a?reconnect=true